### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by kettanaito** [cloudflare/capnweb#73]
Hi!

Thank you for an awesome library. I'm trying to wrap my head around it to see if we can use it for cross-process request interception in [MSW](https://mswjs.io). While working on it, I got the following error:

```
ReferenceError: navigator is not defined
 ❯ node_modules/.pnpm/capnweb@0.1.0/node_modules/capnweb/src/core.ts:15:25
 ❯ src/core/remote/sender.ts:1:1
```

It looks like the library relies on the `navigator` a bit optimistically:

https://github.com/cloudflare/capnweb/blob/7c4207a4830c5cb50d1c1590cfd4fa22cf50b129/src/core.ts#L15

This means **it cannot run in Node.js** (there's no `navigator` there). I presume this is a bug but would like to get your opinion on it first before opening a pull request. A simple `typeof navigator !== 'undefined'` check would be enough to enable Node.js support (at least to unblock this error).

**Comment by kentonv** [comment]
> This means it cannot run in Node.js (there's no navigator there). 

Sure there is:

<img width="466" height="119" alt="Image" src="https://github.com/user-attachments/assets/95991366-460e-43f3-b004-1bec8398c63c" />

And of course we have tests for Node.js, and they pass.

All major runtimes have this API.

But I agree we shouldn't require `navigator` as it's not technically part of ecmascript and we ought to support platforms that don't have it.

But probably the fix for #23 will remove this check anyway (preferring instead to use a "conditional export" in package.json), so that should fix the issue?

**Comment by kettanaito** [comment]
Oh, so it has been added in the recent versions, I see. Node.js v20.19.4 still throws an error:

```
Welcome to Node.js v20.19.4.
Type ".help" for more information.
> navigator
Uncaught ReferenceError: navigator is not defined
```

Maybe I'm running an older v20 version, let me check. 

_Edit_: Nae, consistently missing in v20.

**Comment by kentonv** [comment]
This was fixed by #82, which will land in a release in the next 24 hours.
